import "./styles.css";
import "./splash.css";
import "./splash-reference.css";
import "./splash-brand.css";

const nav = ["Home", "Projects", "Story Bible", "Character Bible", "Design Bible", "Locations", "Props", "Storyboards", "AI Director", "Motion Graphics", "Timeline", "Model Hub", "Media Library", "Templates", "Settings"];
const icons = ["⌂", "▦", "◈", "♙", "✦", "⌖", "◇", "▤", "✧", "▥", "≋", "◉", "▧", "✺", "⚙"];
const blank = () => ({ name: "Untitled Story", logline: "", genre: "", tone: "", characters: [], locations: [], shots: [], style: "", updatedAt: new Date().toISOString() });
let project = blank(); let filePath = ""; let dirty = false; let active = "Home"; let showingSplash = true;
const $ = (s) => document.querySelector(s);
function markDirty() { dirty = true; window.storyMakerDesktop?.setDirty(true); $("#saveState").textContent = "Unsaved changes"; $("#saveState").classList.add("dirty"); }
function toast(text) { $("#toast").textContent = text; $("#toast").classList.add("show"); setTimeout(() => $("#toast").classList.remove("show"), 2600); }
function render() { $("#app").innerHTML = `<div class="shell"><aside class="sidebar"><div class="brand"><div class="brand-orbit">✦</div><div><b>WHEELBARROW</b><span>STUDIOS</span></div></div><button class="quick-create" id="quickCreate">＋ New story</button><nav>${nav.map((item, i) => `<button class="nav-item ${active === item ? "active" : ""}" data-nav="${item}"><i>${icons[i]}</i><span>${item}</span>${["AI Director", "Timeline"].includes(item) ? "<em>NEW</em>" : ""}</button>`).join("")}</nav><div class="sidebar-bottom"><div class="storage"><span class="status-dot"></span><span><b>Studio ready</b><small>Local workspace</small></span></div><button class="profile">◎ <span>Director workspace</span>⌄</button></div></aside><main class="main"><header class="topbar"><div class="crumb"><span>STORY MAKER</span><b>/</b><strong>${project.name}</strong></div><div class="top-actions"><button class="icon-button" id="searchBtn">⌕</button><button class="icon-button" id="notifyBtn">♢</button><button class="ghost" id="helpBtn">Guide</button><button class="primary" id="saveBtn">Save story</button><div id="saveState">${dirty ? "Unsaved changes" : "All changes saved"}</div></div></header><section class="content">${active === "Home" ? home() : active === "Projects" ? projects() : active === "Settings" ? settings() : workspace(active)}</section></main><div id="toast"></div></div>`; bind(); }
function home() { return `<div class="welcome"><div><p class="eyebrow">GOOD EVENING, DIRECTOR</p><h1>Make something<br><span>worth remembering.</span></h1><p class="lede">A calm, cinematic workspace for building stories with continuity, intention, and a little magic.</p><div class="hero-actions"><button class="primary large" id="startBtn">＋ Start a new story</button><button class="ghost large" id="openBtn">Open a story</button></div></div><div class="hero-art"><div class="hero-glow"></div><div class="hero-copy"><span>THE STORY<br>COMES FIRST</span><small>Build the world. Find the feeling.</small></div></div></div><div class="section-head"><div><p class="eyebrow">YOUR STUDIO</p><h2>Pick up where you left off</h2></div><button class="text-link" data-nav="Projects">View all projects →</button></div><div class="dashboard-grid"><article class="project-card featured"><div class="card-image"><span>◈</span></div><div class="card-body"><span class="pill">IN PROGRESS</span><h3>${project.name === "Untitled Story" ? "Your next story" : project.name}</h3><p>${project.logline || "Your story world is waiting for its first scene."}</p><div class="progress"><span style="width: 18%"></span></div><small>18% explored · Continue building</small></div></article><article class="inspiration"><p class="eyebrow">CREATIVE PROMPT</p><h3>What if the thing<br>you fear is the<br>thing that saves you?</h3><button class="text-link">Use as a spark ↗</button></article><article class="health"><div class="section-head"><h3>Production health</h3><span class="health-score">92</span></div><div class="health-line"><span style="width:92%"></span></div><p>Your story foundation is strong. Define a visual language to unlock the next layer.</p><div class="health-row"><span>Story foundation</span><b>Ready</b></div><div class="health-row"><span>Visual continuity</span><b class="warn">In progress</b></div></article></div>`; }
function projects() { return `<div class="page-heading"><div><p class="eyebrow">WORKSPACE</p><h1>Projects</h1><p class="lede">Every story begins somewhere. Keep your worlds close.</p></div><button class="primary" id="newProjectBtn">＋ New story</button></div><div class="project-list"><article class="project-row" id="projectRow"><div class="project-thumb"><span>◈</span></div><div><span class="pill">IN PROGRESS</span><h3>${project.name}</h3><p>${project.logline || "A new world taking shape."}</p></div><div class="row-meta"><span>Updated just now</span><button class="ghost" id="openProjectBtn">Open</button></div></article><div class="empty-project"><span>✦</span><h3>Your next great story belongs here.</h3><p>Create a project to start building its world.</p><button class="text-link" id="emptyNew">Create a story →</button></div></div>`; }
function workspace(title) { const descriptions = { "Story Bible": "The emotional and narrative source of truth for your world.", "Character Bible": "Build people who feel alive before they ever enter a scene.", "Design Bible": "Give your story a visual language it can keep.", Locations: "Places carry memory. Build the spaces your story needs.", Props: "The objects that make a world feel lived in.", Storyboards: "See the story before you make the shot.", "AI Director": "Quiet guidance for stronger scenes, clearer intent, and continuity.", "Motion Graphics": "Typography, titles, and movement with a point of view.", Timeline: "Shape the rhythm of the story.", "Model Hub": "Choose the right creative instrument for the moment.", "Media Library": "A home for every reference, take, and iteration.", Templates: "Beautiful starting points, ready when you are." }; return `<div class="page-heading"><div><p class="eyebrow">STORY MAKER / ${title.toUpperCase()}</p><h1>${title}</h1><p class="lede">${descriptions[title] || "Make the studio feel like yours."}</p></div><button class="primary" id="workspaceAction">＋ Add to ${title.toLowerCase()}</button></div><div class="workspace-grid"><div class="workspace-panel large-panel"><div class="panel-orbit">${title === "AI Director" ? "✧" : "◈"}</div><h2>${title === "Story Bible" ? "Start with the feeling." : title === "Character Bible" ? "No characters yet." : `Your ${title.toLowerCase()} is ready to take shape.`}</h2><p>${title === "Story Bible" ? "A clear emotional north star makes every later decision easier. Tell us what this story wants to say." : "This space will stay connected to the same production data, so every decision carries forward."}</p><button class="ghost" id="workspaceAction2">Begin here →</button></div><div class="workspace-panel insight"><p class="eyebrow">CONNECTED CONTEXT</p><div class="context-row"><span>Story</span><b>${project.name}</b></div><div class="context-row"><span>Style</span><b>${project.style || "Not defined yet"}</b></div><div class="context-row"><span>Continuity</span><b class="warn">Needs attention</b></div><div class="divider"></div><p class="muted">Everything you create here becomes part of the story's living memory.</p></div></div>`; }
function settings() { return `<div class="page-heading"><div><p class="eyebrow">STORY MAKER / PREFERENCES</p><h1>Settings</h1><p class="lede">Shape the studio around the way you think.</p></div></div><div class="settings-card"><h3>Workspace preferences</h3><label>Project autosave<select id="autosave"><option>On — save continuously</option><option>Off — save manually</option></select></label><label>Creative mode<select><option>Simple — guide me</option><option>Studio — show everything</option></select></label><label>Accent atmosphere<select><option>Violet / Blue</option><option>Amber / Rose</option></select></label><p class="muted">Your stories are saved locally on this Windows device. API connections can be added later.</p></div>`; }
function newStory() { const name = prompt("What should we call this story?", "Untitled Story"); if (!name) return; project = { ...blank(), name: name.trim() }; filePath = ""; dirty = true; showingSplash = false; $("#splashOverlay")?.remove(); active = "Story Bible"; render(); markDirty(); }
async function save(as = false, close = false) { const result = await window.storyMakerDesktop?.saveProject({ project, filePath: as ? "" : filePath, saveAs: as, suggestedName: `${project.name.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "untitled-story"}.storymaker` }); if (!result || result.canceled) { if (close) await window.storyMakerDesktop?.cancelClose(); return false; } filePath = result.filePath; dirty = false; window.storyMakerDesktop?.setDirty(false); $("#saveState").textContent = "All changes saved"; $("#saveState").classList.remove("dirty"); toast("Story saved safely."); if (close) await window.storyMakerDesktop?.closeAfterSave(); return true; }
async function open() { const result = await window.storyMakerDesktop?.openProject(); if (!result || result.canceled) return; project = { ...blank(), ...result.project }; filePath = result.filePath; dirty = false; showingSplash = false; $("#splashOverlay")?.remove(); active = "Home"; render(); toast(result.recovered ? "Recovered the last safe backup." : "Story opened."); }
function bind() { document.querySelectorAll("[data-nav]").forEach((el) => el.addEventListener("click", () => { active = el.dataset.nav; render(); })); $("#quickCreate")?.addEventListener("click", newStory); $("#startBtn")?.addEventListener("click", newStory); $("#newProjectBtn")?.addEventListener("click", newStory); $("#emptyNew")?.addEventListener("click", newStory); $("#openBtn")?.addEventListener("click", open); $("#openProjectBtn")?.addEventListener("click", open); $("#saveBtn")?.addEventListener("click", () => save()); $("#helpBtn")?.addEventListener("click", () => toast("Story Maker keeps the technical complexity quiet so you can stay with the story.")); $("#workspaceAction")?.addEventListener("click", () => toast("This connected studio surface is ready for your next decision.")); $("#workspaceAction2")?.addEventListener("click", () => toast("Begin with one clear creative intention.")); }
function showSplashOverlay() { if (!showingSplash) return; document.body.insertAdjacentHTML("beforeend", `<div class="splash" id="splashOverlay"><div class="splash-backdrop"></div><div class="splash-inner"><div class="splash-mark">✦</div><p class="eyebrow">WHEELBARROW STUDIOS PRESENTS</p><h1>Story<br><span>Maker</span></h1><p class="splash-line">Build the world. Find the feeling.</p><div class="splash-actions"><button class="primary large" id="splashNew">＋ Begin a new story</button><button class="ghost large" id="splashOpen">Open an existing story</button></div><button class="splash-enter" id="enterStudio">Enter the studio →</button></div><div class="splash-footer">A visual production studio for stories with a soul <span>●</span> v0.1</div></div>`); $("#splashNew").addEventListener("click", newStory); $("#splashOpen").addEventListener("click", open); $("#enterStudio").addEventListener("click", () => { showingSplash = false; $("#splashOverlay").remove(); }); }
function showSplashOverlay() { if (!showingSplash) return; document.body.insertAdjacentHTML("beforeend", `<div class="splash" id="splashOverlay"><div class="splash-backdrop"></div><div class="splash-inner"><div class="splash-mark">S</div><p class="eyebrow">WHEELBARROW STUDIOS PRESENTS</p><h1>STORYMAKER</h1><p class="splash-subtitle">AI-NATIVE FILM STUDIO</p><p class="splash-line">Start with a story.<br>Direct every layer. Finish with a film.</p><div class="splash-actions"><button class="primary large" id="splashNew">CREATE NEW PROJECT</button><button class="ghost large" id="splashOpen">OPEN PROJECT</button></div><div class="splash-features"><span>◈<small>SCRIPT TO FILM</small></span><span>♙<small>ACTING & PERFORMANCE</small></span><span>✦<small>VISUAL STYLES</small></span><span>▤<small>CINEMATIC CONTROL</small></span><span>≋<small>MOTION GRAPHICS</small></span><span>♫<small>AUDIO & MUSIC</small></span></div><button class="splash-enter" id="enterStudio">Enter studio →</button></div><div class="splash-mode studio">✦ STUDIO MODE<small>For filmmakers & pros</small></div><div class="splash-mode simple">✧ SIMPLE MODE<small>For creators & beginners</small></div><div class="splash-footer">© 2026 Wheelbarrow Studios</div></div>`); $("#splashNew").addEventListener("click", newStory); $("#splashOpen").addEventListener("click", open); $("#enterStudio").addEventListener("click", () => { showingSplash = false; $("#splashOverlay").remove(); }); }
window.storyMakerDesktop?.onCommand((command) => { if (command === "new") newStory(); if (command === "open") open(); if (command === "save") save(); if (command === "save-as") save(true); if (command === "save-and-close") save(false, true); if (command === "settings") { active = "Settings"; render(); } if (command === "help") toast("Story Maker Guide: start with the feeling, then build the world around it."); if (command === "palette") toast("Command Palette coming into focus."); });
render();
showSplashOverlay();
