const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("storyMakerDesktop", {
  saveProject: (payload) => ipcRenderer.invoke("project:save", payload),
  openProject: () => ipcRenderer.invoke("project:open"),
  importStorySource: () => ipcRenderer.invoke("source:import"),
  importStoryText: (payload) => ipcRenderer.invoke("source:import-text", payload),
  readClipboardText: () => ipcRenderer.invoke("clipboard:read-text"),
  runSourceOcr: (payload) => ipcRenderer.invoke("source:run-ocr", payload),
  importMedia: () => ipcRenderer.invoke("media:import"),
  setDirty: (value) => ipcRenderer.invoke("app:setDirty", value),
  closeAfterSave: () => ipcRenderer.invoke("app:close-after-save"),
  cancelClose: () => ipcRenderer.invoke("app:cancel-close"),
  providerStatus: () => ipcRenderer.invoke("providers:status"),
  providerDiagnostics: () => ipcRenderer.invoke("providers:diagnostics"),
  generationJobs: () => ipcRenderer.invoke("generation:jobs"),
  recoverGeneratedAssets: (payload) => ipcRenderer.invoke("generation:recover-assets", payload),
  saveMediaCopy: (payload) => ipcRenderer.invoke("media:save-copy", payload),
  upscaleMedia: (payload) => ipcRenderer.invoke("media:upscale", payload),
  deleteMediaFile: (payload) => ipcRenderer.invoke("media:delete-file", payload),
  logGenerationBlocked: (payload) => ipcRenderer.invoke("generation:log-blocked", payload),
  saveProviderKey: (payload) => ipcRenderer.invoke("providers:save-key", payload),
  verifyProvider: (provider) => ipcRenderer.invoke("providers:verify", provider),
  requestDirectorReview: (project) => ipcRenderer.invoke("director:review", project),
  analyzeStory: (payload) => ipcRenderer.invoke("story:analyze", payload),
  suggestScriptImprovements: (project) => ipcRenderer.invoke("story:suggest-improvements", project),
  translateCreativeInfluence: (payload) => ipcRenderer.invoke("story:creative-influence", payload),
  recommendStyles: (payload) => ipcRenderer.invoke("story:recommend-styles", payload),
  planShots: (payload) => ipcRenderer.invoke("story:plan-shots", payload),
  generateSceneImage: (payload) => ipcRenderer.invoke("scene:generate-image", payload),
  generateShotImage: (payload) => ipcRenderer.invoke("shot:generate-image", payload),
  submitShotVideo: (payload) => ipcRenderer.invoke("shot:submit-video", payload),
  pollShotVideo: (payload) => ipcRenderer.invoke("shot:poll-video", payload),
  preflightShot: (payload) => ipcRenderer.invoke("shot:preflight", payload),
  exportProductionPackage: (payload) => ipcRenderer.invoke("project:export-package", payload),
  deliveryCapabilities: () => ipcRenderer.invoke("delivery:capabilities"),
  renderVisualPreview: (payload) => ipcRenderer.invoke("delivery:render-preview", payload),
  requestDriftCheck: (payload) => ipcRenderer.invoke("drift:check", payload),
  onCommand: (callback) => { const listener = (_event, command) => callback(command); ipcRenderer.on("menu-command", listener); return () => ipcRenderer.removeListener("menu-command", listener); }
});
